### ISSUE TITLE
OpenSource (GPLv3 compatible) Small JavaScript Library to highlight GitHub's notes in HTML preview.

### ISSUE THREAD

**Issue by igormironchik** [igormironchik/md-editor#2]
* [Task](#ts)
  * [CSS](#css)
  * [Additional information](#additional-information)
  * [Some rendered examples](#some-rendered-examples)

# TS <div id="ts"></div>

Develop a small JavaScript library to style blockquotes in HTML preview, like on GitHub if they have
`[!NOTE]`, `[!TIP]`, `[!IMPORTANT]`, `[!WARNING]`, `[!CAUTION]`.

This library should be in one `*.js` file that can be loaded in HTML with `<script>` tag.
This library should has one function that will get `document.body` and will do
modifications according to the following rules.

License of this library should be any `GPLv3` compatible.

In HTML I have, for example:

```html
<blockquote><p> [!IMPORTANT] 
 text </p></blockquote>
```

And I need to replace such blockquotes with:

```html
<blockquote class="markdown-alert markdown-alert-important">
<p class="markdown-alert-title"><svg>...</svg>...</p>
<p> text </p></blockquote>
```

## CSS <div id="css"></div>

CSS for alerts:

```css
.markdown-body .markdown-alert {
  padding: var(--base-size-8) var(--base-size-16);
  margin-bottom: 16px;
  color: inherit;
  border-left: .25em solid var(--color-border-default);
}

.markdown-body .markdown-alert>:first-child {
  margin-top: 0;
}

.markdown-body .markdown-alert>:last-child {
  margin-bottom: 0;
}

.markdown-body .markdown-alert .markdown-alert-title {
  display: flex;
  font-weight: var(--base-text-weight-medium, 500);
  align-items: center;
  line-height: 1;
}

.markdown-body .markdown-alert.markdown-alert-note {
  border-left-color: var(--color-accent-emphasis);
}

.markdown-body .markdown-alert.markdown-alert-note .markdown-alert-title {
  color: var(--color-accent-fg);
}

.markdown-body .markdown-alert.markdown-alert-important {
  border-left-color: var(--color-done-emphasis);
}

.markdown-body .markdown-alert.markdown-alert-important .markdown-alert-title {
  color: var(--color-done-fg);
}

.markdown-body .markdown-alert.markdown-alert-warning {
  border-left-color: var(--color-attention-emphasis);
}

.markdown-body .markdown-alert.markdown-alert-warning .markdown-alert-title {
  color: var(--color-attention-fg);
}

.markdown-body .markdown-alert.markdown-alert-tip {
  border-left-color: var(--color-success-emphasis);
}

.markdown-body .markdown-alert.markdown-alert-tip .markdown-alert-title {
  color: var(--color-success-fg);
}

.markdown-body .markdown-alert.markdown-alert-caution {
  border-left-color: var(--color-danger-emphasis);
}

.markdown-body .markdown-alert.markdown-alert-caution .markdown-alert-title {
  color: var(--color-danger-fg);
}
```

## Additional information <div id="additional-information"></div>

> [!NOTE]
> Only top-level `<blockquote>` should be processed, i.e. if blockquote has other
> blockquote as child, child should not be processed, if blockquote is not a top-level HTML
> tag in first `<article>` tag, where this `<article>` tag will be as:
>
> ```html
> <body><div><article>...</article></div></body>
> ```
> 
> it should not be processed.

> [!NOTE]
> `<blockquote>` tag should be modified only if it has marker in first `<p>` tag on first
> line, and marker should be alone on the line in HTML, i.e. a following paragraph
> should be modified:
>
> ```html
> <p> [!NOTE]
> text </p>
> ```
>
> Because marker `[!NOTE]` is alone and in first paragraph, and on first line.
>
> Bellow will be some examples...

> [!TIP]
> Following blockquote should not be modified as it has two markers on first line.
>
> ```html
> <blockquote><p> [!TIP] [!NOTE] </p></blockquote>
> ```

> [!TIP]
> Following blockquote should be modified.
>
> ```html
> <blockquote><p> [!TIP] </p><p> Text </p></blockquote>
> ```

> [!TIP]
> Following blockquote should be modified as on first line in first paragraph
> only one marker.
>
> ```html
> <blockquote><p> [!NOTE]
>  [!TIP] </p></blockquote>
> ```
> 
> And here `[!NOTE]` marker should be used for modification, and marker `[!TIP]`
> should be stay as text, as it was.

> [!NOTE]
> [Link to GitHub's discussion about highlighted blockquotes](https://github.com/orgs/community/discussions/16925)

## Some rendered examples <div id="some-rendered-examples"></div>

<table style="width:100%">
<tr>
<td>

> [!NOTE]
> text on other line - OK

</td>

<td>

```html
<blockquote>
<p>[!NOTE]
text on other line - OK</p>
</blockquote>
```

</td>

</tr>

<tr>
<td>

> [!NOTE] with text doesn't work

</td>

<td>

```html
<blockquote>
<p>[!NOTE] with text doesn't work</p>
</blockquote>
```

</td>
</tr>

<tr>
<td>

> text on first line - doesn't work
> [!TIP]

</td>

<td>

```html
<blockquote>
<p>text on first line - doesn't work
[!TIP]</p>
</blockquote>
```

</td>
</tr>

<tr>
<td>

> [!TIP]
> 
> text in different second paragraph - OK

</td>
<td>

```html
<blockquote>
<p>[!TIP]</p>
<p>text in different second paragraph - OK</p>
</blockquote>
```

</td>
</tr>

<tr>
<td>

> [!NOTE] [!TIP]
> doesn't wotk - 2 markers on first line

</td>

<td>

```html
<blockquote>
<p>[!NOTE] [!TIP]
doesn't wotk - 2 markers on first line</p>
</blockquote>
```

</td>
</tr>

<tr>
<td>

> [!TIP]
> [!NOTE]
> works, on first line only 1 marker - OK

</td>
<td>

```html
<blockquote>
<p>[!TIP]
[!NOTE]
works, on first line only 1 marker - OK</p>
</blockquote>
```

</td>
</tr>

<tr>
<td>

> [!TIP]
>> [!NOTE]
>> text
>
> text

</td>
<td>

```html
<blockquote>
<p>[!TIP]</p>
<blockquote>
<p>[!NOTE]
text</p>
</blockquote>
<p>text</p>
</blockquote>
```

</td>
</tr>

<tr>
<td>

* List

  > [!TIP]
  > Text

</td>
<td>

```html
<ul>
<li>
<p>List</p>
<blockquote>
<p>[!TIP]
Text</p>
</blockquote>
</li>
</ul>
```

</td>
</tr>
</table>
